# Generated by Django 5.2.14 on 2026-05-16 04:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('status', models.CharField(choices=[('issued', 'issued'), ('activated', 'activated'), ('used', 'used'), ('expired', 'expired')], default='issued', max_length=16)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activated_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('countdown_completed', models.BooleanField()),
            ],
            options={
                'db_table': 'coupon_usage',
            },
        ),
        migrations.CreateModel(
            name='RouletteConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'roulette_config',
            },
        ),
        migrations.CreateModel(
            name='RoulettePrize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('probability_bp', models.IntegerField()),
                ('expiry_days', models.IntegerField(blank=True, null=True)),
                ('rarity', models.CharField(choices=[('normal', 'ノーマル'), ('rare', 'レア'), ('super_rare', '超レア'), ('legendary', '伝説')], max_length=16)),
            ],
            options={
                'db_table': 'roulette_prize',
            },
        ),
        migrations.CreateModel(
            name='RouletteSpin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_awarded', models.IntegerField()),
                ('spun_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'roulette_spin',
            },
        ),
    ]
