# Generated by Django 5.2.14 on 2026-05-16 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('stores', '0001_initial'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='stores.client'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='stores.store'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='coupon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='usage', to='coupons.coupon'),
        ),
        migrations.AddField(
            model_name='rouletteconfig',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roulette_configs', to='stores.store'),
        ),
        migrations.AddField(
            model_name='rouletteprize',
            name='roulette_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='coupons.rouletteconfig'),
        ),
        migrations.AddField(
            model_name='roulettespin',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roulette_spins', to='stores.client'),
        ),
        migrations.AddField(
            model_name='roulettespin',
            name='prize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spins', to='coupons.rouletteprize'),
        ),
        migrations.AddField(
            model_name='roulettespin',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roulette_spins', to='stores.store'),
        ),
        migrations.AddField(
            model_name='roulettespin',
            name='survey_response',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='roulette_spin', to='surveys.surveyresponse'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='roulette_spin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='coupon', to='coupons.roulettespin'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['client', 'status'], name='coupon_client__a70ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['store', 'status'], name='coupon_store_i_46470d_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['status', 'expires_at'], name='coupon_status_941b40_idx'),
        ),
    ]
