# Generated by Django 5.2.14 on 2026-05-16 04:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_templates', to='stores.store')),
            ],
            options={
                'db_table': 'survey_template',
                'unique_together': {('store', 'version')},
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase1_completed_at', models.DateTimeField(blank=True, null=True)),
                ('phase2_completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_duration_sec', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_responses', to='stores.client')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_responses', to='stores.store')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to='stores.clientvisit')),
                ('survey_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='surveys.surveytemplate')),
            ],
            options={
                'db_table': 'survey_response',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.SmallIntegerField()),
                ('order_no', models.SmallIntegerField()),
                ('question_type', models.CharField(choices=[('choice', 'choice'), ('slider', 'slider'), ('boolean', 'boolean')], max_length=16)),
                ('body_i18n', models.JSONField()),
                ('options_i18n', models.JSONField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('survey_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.surveytemplate')),
            ],
            options={
                'db_table': 'question',
                'ordering': ['phase', 'order_no'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_int', models.SmallIntegerField(blank=True, null=True)),
                ('value_text', models.CharField(blank=True, max_length=64)),
                ('answered_at', models.DateTimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='surveys.question')),
                ('survey_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyresponse')),
            ],
            options={
                'db_table': 'answer',
                'unique_together': {('survey_response', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['store', 'created_at'], name='survey_resp_store_i_c8b951_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('survey_template', 'phase', 'order_no')},
        ),
    ]
