# Generated by Django 5.2.14 on 2026-05-16 04:23

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name_ja', models.CharField(max_length=64)),
                ('name_en', models.CharField(blank=True, max_length=64)),
                ('frequency_type', models.CharField(choices=[('high', 'high'), ('mid', 'mid'), ('low', 'low')], max_length=16)),
                ('active_metric', models.CharField(choices=[('WAU', 'WAU'), ('MAU', 'MAU'), ('QAU', 'QAU')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'business_category',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('total_points', models.IntegerField(default=0)),
                ('available_points', models.IntegerField(default=0)),
                ('locale_code', models.CharField(blank=True, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('sms_2fa_enabled', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'owner',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('postal_code', models.CharField(blank=True, max_length=16)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('currency_code', models.CharField(default='JPY', max_length=3)),
                ('locale_code', models.CharField(default='ja_JP', max_length=8)),
                ('logo_url', models.CharField(blank=True, max_length=512)),
                ('brand_color', models.CharField(blank=True, max_length=7)),
                ('google_place_id', models.CharField(blank=True, max_length=128)),
                ('instagram_handle', models.CharField(blank=True, max_length=64)),
                ('line_official_id', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='stores.businesscategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('qr_scanned', 'qr_scanned'), ('survey_started', 'survey_started'), ('question_answered', 'question_answered'), ('survey_phase1_completed', 'survey_phase1_completed'), ('survey_completed', 'survey_completed'), ('roulette_spun', 'roulette_spun'), ('pwa_install_prompted', 'pwa_install_prompted'), ('pwa_installed', 'pwa_installed'), ('coupon_issued', 'coupon_issued'), ('coupon_activated', 'coupon_activated'), ('coupon_used_start', 'coupon_used_start'), ('coupon_used_confirmed', 'coupon_used_confirmed'), ('coupon_expired', 'coupon_expired'), ('notification_sent', 'notification_sent'), ('notification_opened', 'notification_opened'), ('revisit', 'revisit')], max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('payload', models.JSONField(default=dict)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='stores.client')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='stores.store')),
            ],
            options={
                'db_table': 'event_log',
            },
        ),
        migrations.CreateModel(
            name='ClientVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visited_at', models.DateTimeField()),
                ('visit_number', models.IntegerField()),
                ('companions', models.SmallIntegerField(blank=True, null=True)),
                ('referral_source', models.CharField(blank=True, choices=[('map', '地図'), ('referral', '紹介'), ('regular', '常連'), ('passerby', '通りかかり')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='stores.client')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='stores.store')),
            ],
            options={
                'db_table': 'client_visit',
            },
        ),
        migrations.CreateModel(
            name='PwaInstall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('desktop', 'Desktop')], max_length=16)),
                ('installed_at', models.DateTimeField()),
                ('push_token', models.CharField(blank=True, max_length=512)),
                ('uninstalled_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pwa_installs', to='stores.client')),
            ],
            options={
                'db_table': 'pwa_install',
                'indexes': [models.Index(fields=['client', 'uninstalled_at'], name='pwa_install_client__2ad3e9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['owner'], name='store_owner_i_2eb4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['business_category'], name='store_busines_f723da_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['latitude', 'longitude'], name='store_latitud_160270_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['store', 'occurred_at'], name='event_log_store_i_ef5094_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['event_type', 'occurred_at'], name='event_log_event_t_7ebc0f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['client', 'occurred_at'], name='event_log_client__0a95c4_idx'),
        ),
        migrations.AddIndex(
            model_name='clientvisit',
            index=models.Index(fields=['client', 'store'], name='client_visi_client__09c542_idx'),
        ),
        migrations.AddIndex(
            model_name='clientvisit',
            index=models.Index(fields=['store', 'visited_at'], name='client_visi_store_i_402bba_idx'),
        ),
    ]
